
services:
  - type: web
    name: complycall
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir webapp --bind 0.0.0.0:$PORT --timeout 180 app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: ANON_SALT        
        generateValue: true
      - key: ANTHROPIC_API_KEY  # optional
        sync: false
      - key: ELEVENLABS_API_KEY # optional 
        sync: false
